service:
  name: apiserver
  type: ClusterIP
  externalPort: 80
  internalPort: 8020
istio:
  enabled: true
  release:
    enabled: false
  tags:
    enabled: true
routes:
  v1:
    weight: 80
    release: apiserver-v1
    tag: pr1-07d3ba5
  v2:
    weight: 20
    release: apiserver-v2
    tag:  master-4c5a465