{{- if .Values.istio.enabled -}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /getconfig
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.service.externalPort }}
      - path: /test
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.service.externalPort }}
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: {{ .Chart.Name }}-prod
spec:
  destination:
    name: {{ template "fullname" . }}
  precedence: 1
  route:
  - labels:
      tag: {{ .Values.image.v1.tag | quote }}
    weight: {{ .Values.image.v1.weight }}
  - labels:
      tag: {{ .Values.image.v2.tag | quote }}
    weight: {{ .Values.image.v2.weight }}
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: {{ .Chart.Name }}-v1
spec:
  destination:
    name: {{ template "fullname" . }}
  precedence: 3
  match:
    request:
      headers:
        ver-{{ template "fullname" . }}:
          prefix: v1
  route:
  - labels:
      version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: {{ .Chart.Name }}-v2
spec:
  destination:
    name: {{ template "fullname" . }}
  precedence: 3
  match:
    request:
      headers:
        ver-{{ template "fullname" . }}:
          prefix: v2
  route:
  - labels:
      version: v2
---
{{- end }}